name: Deploy MySQL Bicep
run-name: Deploy MySQL Flexible Server (Bicep)
on:
  workflow_dispatch: # 支持手动触发
  push:
    branches: [ main ]
    paths:
      - 'db-flexible-server.bicep'

permissions:
  contents: read

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal with creds JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.TSSNKUR_SECRET }}

      - name: Validate current Azure subscription
        run: az account show --query id -o tsv

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group rg-tssnkur-prod \
            --template-file ./db-flexible-server.bicep
